### PR TITLE
course_revision: replace content w/ description

### LINKED ISSUE #88: Review CourseRevision
Seems like Course incorrectly query a non-existing "content" field instead of "description". We should review that.

### PR DESCRIPTION
**Pull request by elbotho**
Hm... that should be it? 
Seems a bit easy ;)
Tested with 30700, could not find a `CourseRevision` with description in the local data..

closes #88

(also some updates to Cargo.lock slipped in)

### CODE REVIEW

File: src/uuid/model/entity_revision/course_revision.rs [hunk 1]
```diff
@@ -6,21 +6,21 @@ use super::abstract_entity_revision::AbstractEntityRevision;
 #[serde(rename_all = "camelCase")]
 pub struct CourseRevision {
     title: String,
-    content: String,
+    description: String,
```
Comment (inyono) [inline src/uuid/model/entity_revision/course_revision.rs:9]: This should still be `content` to not introduce a breaking change.

**Review by inyono — CHANGES_REQUESTED** [review]

File: src/uuid/model/entity_revision/course_revision.rs (hunk 1 above)
Comment (elbotho) [reply src/uuid/model/entity_revision/course_revision.rs:9]: ah I see, just change the field it expects from the db then.

Comment (inyono) [reply src/uuid/model/entity_revision/course_revision.rs]: The contract tests catched that btw, yay 🎉

**Review by inyono — APPROVED** [review]
